import logging
from django.db.models import Count
from import_engine.domain.models import ImportJob, ImportLog

logger = logging.getLogger(__name__)


class DiagnosticService:
    """Analyzes completed import jobs to generate performance summaries."""

    @classmethod
    def generate_report(cls, job_id: str) -> dict:
        """Generates a performance and error profile for a job."""
        try:
            job = ImportJob.objects.get(id=job_id)

            # 1. Error Analysis (Top 5 failure reasons)
            error_summary = (
                ImportLog.objects.filter(job=job)
                .values("errors")
                .annotate(count=Count("id"))
                .order_by("-count")[:5]
            )

            # 2. Performance Summary
            duration = 0
            if job.started_at and job.finished_at:
                duration = (job.finished_at - job.started_at).total_seconds()

            report = {
                "job_id": str(job.id),
                "model": job.model_name,
                "status": job.status,
                "metrics": {
                    "total_rows": job.total_rows,
                    "success": job.success_count,
                    "failure": job.failure_count,
                    "duration_seconds": round(duration, 2),
                    "avg_throughput_rows_sec": round(job.throughput_rows_sec, 2),
                },
                "top_errors": [
                    {
                        "reason": list(err["errors"].values())[0]
                        if isinstance(err["errors"], dict)
                        else str(err["errors"]),
                        "count": err["count"],
                    }
                    for err in error_summary
                ],
            }

            logger.info(f"Diagnostic Report generated for Job {job.id}")
            return report

        except ImportError as e:
            logger.error(f"Failed to generate diagnostic report for {job_id}: {e}")
            return {"error": "Reporting failed"}
        except Exception as e:
            logger.exception(f"Unexpected error in diagnostic generation: {e}")
            return {"error": str(e)}

    @classmethod
    def format_report_as_markdown(cls, report: dict) -> str:
        """Helper to create a human-readable summary for the admin/logs."""
        if "error" in report:
            return "## ❌ Diagnostic Report Failed"

        m = report["metrics"]
        errs = "\n".join(
            [
                f"- **{e['count']}x**: {e['reason']}"
                for e in report.get("top_errors", [])
            ]
        )

        return f"""
# 📋 Import Diagnostic Report: {report["job_id"]}

### 📈 Performance Summary
- **Status**: {report["status"]}
- **Total Rows**: {m["total_rows"]}
- **Success Rate**: {round((m["success"] / m["total_rows"]) * 100, 2) if m["total_rows"] > 0 else 0}%
- **Avg Speed**: {m["avg_throughput_rows_sec"]} rows/sec
- **Total Duration**: {m["duration_seconds"]}s

### 🚨 Top Failure Reasons
{errs if errs else "No errors detected."}

---
Generated by Import Engine Diagnostic Service
"""
